#!/bin/bash

: "
          AUTHOR : GAUTAM CHANDRA SAHA
          DATE & TIME: Thu, November 11,2021 AT 22:03 
          DESCRIPTION:

"


file=""
ufile=""
dirname=""
VERSION=v1.0.3

function exp(){
    export ufile file dirname
        react-bp
}
function check(){
    if [ $2 ]
    then
        if [ -d $PWD/src/$1 ]
        then
        echo $(touch $PWD/src/$1/$2.$3)
        else
        echo $(mkdir $PWD/src/$1)
        echo $(touch $PWD/src/$1/$2.$3)
        fi
    else
        echo "Invalid name"
        exit 0
    fi
}


if [[ "$1" == "-v" || "$1" == "--version" ]]
then
    echo 
    echo "ing $VERSION"
    echo
elif [ -f $PWD/src/index.js ]
then

    if [[ "$2" == "-sc" || "$2" == "-p" ]]
    then
        file=$3
        dirname="screens"
        ufile=$(tr '[:lower:]' '[:upper:]' <<< ${file:0:1})${file:1}
        check "screens" "$ufile" "js"

        if [ "$4" == "-m" ]
        then
                file=$3.module
                check "styles" "$3" "module.css"
        else
                check "styles" "$3" "css"
        fi
        if [[ -z $5 && -z $4 ]] || [[ -z $5 && $4 == "-m" ]]
        then
            exp
        fi
        
    elif [[ "$1" == "g" || "$1" == "gen" ]]
    then
        if [ "$2" == "-c" ]
        then
            file=$3
            dirname="components"
            ufile=$(tr '[:lower:]' '[:upper:]' <<< ${file:0:1})${file:1}
            check "components" "$ufile" "js"
            if [ "$4" == "-m" ]
            then
                    file=$3.module
                    check "styles" "$3" "module.css"
            else
                    check "styles" "$3" "css"
            fi
            if [[ -z $5 && -z $4 ]] || [[ -z $5 && $4 == "-m" ]]
            then
                exp
            fi
            
        elif [ "$2" == "-s" ]
        then
            if [ "$4" == "-m" ]
            then
                check "styles" "$3" "module.css"
            else
                check "styles" "$3" "css"
            fi
           
        # elif [ "$2" == "-scr" ]
        # then
        #     scrUFile=$(tr '[:lower:]' '[:upper:]' <<< ${3:0:1})${3:1}
        #     check "screens" "$scrUFile" "js"

        else
            if [ -d $PWD/src/$2 ]
            then
                echo $(touch $PWD/src/$2/$3)
            else
                echo $(mkdir -p $PWD/src/$2)
                echo $(touch $PWD/src/$2/$3)
            fi
        fi
    fi
else
   echo "This directory does not contain a react project"
fi

