#! /bin/bash

stname=$(echo "$ufile" | tr '[:upper:]' '[:lower:]')

STR="$file"
SUB="module"
if [[ "$STR" == *"$SUB"* ]]
then
  echo "import React from 'react'
import style from '../styles/$file.css'

function $ufile(){
    return (
        <div className={style.$stname}>
             $stname works!
        </div>
    )
}

    
export default $ufile" > $PWD/src/$dirname/$ufile.js

echo ".$stname{}" > $PWD/src/styles/$file.css
else
  echo "import React from 'react'
import '../styles/$file.css'

function $ufile(){
    return (
        <div className=\""$stname"__main\">
            $stname works!
        </div>
    )
}

export default $ufile" > $PWD/src/$dirname/$ufile.js

    echo ".$stname{}" > $PWD/src/styles/$file.css
fi

